### PR TITLE
100% code coverage, specific user data is now pulled from database

### PR DESCRIPTION
**Pull request by jarmeister99**
I added some fixes to the structure of tast_tasks.py, notable a fixture was being overridden

I also changed the tasks GET and POST routes to add or retrieve data for the currently logged in user.

### CODE REVIEW

**Review by Coldice54 — APPROVED** [review]
All of the changes for the tasks and tests seem good, but I think we may want to still keep some get_all tasks function instead of replacing it altogether with a get_tasks_by_user in case we have to do more troubleshooting on that end later.

**Comment by jarmeister99** [comment]
> All of the changes for the tasks and tests seem good, but I think we may want to still keep some get_all tasks function instead of replacing it altogether with a get_tasks_by_user in case we have to do more troubleshooting on that end later.

I agree keeping this function could be useful. I removed it to increase code coverage as I saw it was unused. I'll pull it back in before merging.

**Comment by hunter-waite** [comment]
Good work. I agree with keeping the get-all tasks functionality for testing. Maybe add a few tests in order to get the code coverage up? Approve!

**Comment by jarmeister99** [comment]
> Good work. I agree with keeping the get-all tasks functionality for testing. Maybe add a few tests in order to get the code coverage up? Approve!

Code coverage is currently at 100%, but I'll add in another test when I bring in the code Alex suggested we retrieve. Thanks!

**Comment by martyl1** [comment]
> > Good work. I agree with keeping the get-all tasks functionality for testing. Maybe add a few tests in order to get the code coverage up? Approve!
> 
> Code coverage is currently at 100%, but I'll add in another test when I bring in the code Alex suggested we retrieve. Thanks!

It is looking great! I approve as well. Seems like the tests are going well on the backend.

**Comment by jarmeister99** [comment]
Re-added in Task.get_all() & corresponding test coverage per reviewer comments

**Pull request merged**
