### PR TITLE
Added /tasks/ delete route

### PR DESCRIPTION
**Pull request by Coldice54**
Added functionality to delete tasks from db. Converted _id to str from ObjectId in Task model in order to do so.

### CODE REVIEW

**Comment by jarmeister99** [comment]
LGTM - please remove debugging print statements. There's enough of those floating around (from me LOL) already

**Review by jarmeister99 — COMMENTED** [review]
LGTM - but please remove the debugging print statements. We already have enough of those floating around because of me

**Comment by hunter-waite** [comment]
Good work, can a random user id not just be brute forced for this though?

**Comment by martyl1** [comment]
> Added functionality to delete tasks from db. Converted _id to str from ObjectId in Task model in order to do so.

Glad you got the delete tasks working! That will be very helpful moving forward. I have no suggestions, everything looks good.

**Review by martyl1 — APPROVED** [review]

**Pull request merged**
