### PR TITLE
Fixed issue with password filling and hashing

### PR DESCRIPTION
**Pull request by hunter-waite**
Fixed the issue where when typing a password it would hash as you typed making it impossible to put in an actual password. Login and register routes now working fully.

### CODE REVIEW

**Review by Coldice54 — COMMENTED** [review]
LGTM, I think that the console.log(credentials) might be unnecessary now though

**Comment by hunter-waite** [comment]
> LGTM, I think that the console.log(credentials) might be unnecessary now though

Removed the logging of credentials

**Comment by martyl1** [comment]
> Fixed the issue where when typing a password it would hash as you typed making it impossible to put in an actual password. Login and register routes now working fully.

LGTM as well. Glad that it was a pretty simple fix, so that passwords are now able to be entered and properly hashed! Alex's suggestion was also a proper edit! Good job.

**Comment by jarmeister99** [comment]
Looks good - no comments here that others haven't covered

**Pull request merged**
